services:
  aiostreams:
    image: trongnghiapix/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - '10875:3000'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
