#!/bin/bash
# Script để setup Cloudflare Tunnel với tên domain tùy chỉnh (miễn phí)

echo "=========================================="
echo "  Cloudflare Tunnel - Custom Domain Setup"
echo "=========================================="
echo ""
echo "Bước 1: Tạo tài khoản Cloudflare (miễn phí) tại:"
echo "  https://dash.cloudflare.com/sign-up"
echo ""
echo "Bước 2: Chạy lệnh này để login và tạo tunnel:"
echo "  cd ~/aiostreams"
echo "  ./cloudflared-linux-amd64 tunnel login"
echo ""
echo "Bước 3: Tạo tunnel với tên của bạn:"
echo "  ./cloudflared-linux-amd64 tunnel create aiostreams"
echo ""
echo "Bước 4: Tạo file config:"
echo "  mkdir -p ~/.cloudflared"
echo "  nano ~/.cloudflared/config.yml"
echo ""
echo "Paste nội dung này vào file (thay YOUR_TUNNEL_ID):"
echo "---"
echo "tunnel: YOUR_TUNNEL_ID"
echo "credentials-file: /root/.cloudflared/YOUR_TUNNEL_ID.json"
echo ""
echo "ingress:"
echo "  - hostname: aiostreams.yourdomain.com"
echo "    service: http://localhost:80"
echo "  - service: http_status:404"
echo "---"
echo ""
echo "Bước 5: Chạy tunnel:"
echo "  ./cloudflared-linux-amd64 tunnel run aiostreams"
echo ""
echo "Bước 6: Thêm DNS record vào Cloudflare dashboard"
echo ""
